package com.restmvc.beer_store.entities;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.annotations.UuidGenerator;
import org.hibernate.type.SqlTypes;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Represents a single line item within a BeerOrder.
 * Each line links one Beer to one BeerOrder with a quantity and price snapshot.
 * <p>
 * Relationships:
 * - ManyToOne → BeerOrder: many lines belong to one order (the parent aggregate root).
 * LAZY fetch — when working with a line, we rarely need the full order loaded.
 * optional = false + nullable = false: a line cannot exist without an order.
 * The FK beer_order_id has ON DELETE CASCADE in SQL, so deleting the order
 * removes all lines at the DB level. JPA handles this via CascadeType.ALL +
 * orphanRemoval on the BeerOrder side.
 * <p>
 * - ManyToOne → Beer: references the beer catalog entry.
 * LAZY fetch — beer details are not always needed when processing an order line.
 * optional = false: every line must reference a valid beer.
 * No cascade — Beer is a shared catalog entity managed independently of orders.
 * Deleting a Beer that has order lines would violate the FK constraint (intentional).
 * <p>
 * Price fields:
 * - unitPrice is a snapshot of the beer's price at order creation time.
 * This ensures the order record stays accurate even if the beer's price changes later.
 * - lineSubtotal = unitPrice * orderQuantity, recalculated via recalcSubtotal().
 * The service layer must call recalcSubtotal() before saving when quantity or price changes.
 */
@Getter
@Setter
@Builder
@Entity
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "beer_order_lines",
        indexes = {
                // Speeds up "all lines for a given order" queries (used on every order load).
                @Index(name = "idx_bol_order_id", columnList = "beer_order_id"),
                // Speeds up "all lines containing a specific beer" queries (e.g. stock checks).
                @Index(name = "idx_bol_beer_id", columnList = "beer_id")
        }
)
@EntityListeners(AuditingEntityListener.class)
public class BeerOrderLine {

    // UUID primary key — generated by Hibernate's UuidGenerator (random UUID v4).
    // updatable = false prevents accidental PK change after creation.
    @Id
    @GeneratedValue
    @UuidGenerator
    @JdbcTypeCode(SqlTypes.VARCHAR)
    @Column(name = "beer_order_line_id", updatable = false, nullable = false, columnDefinition = "VARCHAR(36)")
    private UUID id;

    // Optimistic locking — prevents concurrent modification of the same order line.
    // Long (not Integer) to avoid overflow for long-lived entities.
    @Version
    @Column(name = "version")
    private Long version;

    // Managed automatically by Spring Data JPA Auditing.
    // updatable = false ensures created_at is never overwritten after first insert.
    @CreatedDate
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    @LastModifiedDate
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    // Parent order — LAZY because we usually work with lines in the context of a loaded order,
    // so the order is already in the persistence context (no extra query needed).
    // optional = false enforces NOT NULL at the JPA level (mirrors DB constraint).
    @ManyToOne(optional = false, fetch = FetchType.LAZY)
    @JoinColumn(name = "beer_order_id", nullable = false)
    private BeerOrder beerOrder;

    // Reference to the beer catalog. LAZY — beer details are not always needed.
    // No cascade: Beer is a shared entity — deleting an order line must NOT delete the beer.
    // optional = false: every line must reference an existing beer.
    @ManyToOne(optional = false, fetch = FetchType.LAZY)
    @JoinColumn(name = "beer_id", nullable = false)
    private Beer beer;

    // Number of units the customer ordered.
    @Column(name = "order_quantity", nullable = false)
    private Integer orderQuantity;

    // How many units have been physically reserved from stock.
    // Starts null/0, updated by the inventory/allocation service.
    // Nullable: allocation may happen asynchronously after order creation.
    @Column(name = "quantity_allocated")
    private Integer quantityAllocated;

    // Price snapshot: copied from Beer.price at the moment the order is placed.
    // Stored here so the order line stays accurate if the beer's price changes later.
    // NUMERIC(38,2) — exact decimal arithmetic, mandatory for financial values.
    @Column(name = "unit_price", precision = 38, scale = 2, nullable = false)
    private BigDecimal unitPrice;

    // Derived value: unitPrice * orderQuantity.
    // Stored (denormalized) to avoid recalculation on every read and to preserve
    // the exact amount the customer was charged for this line.
    // Must be kept in sync via recalcSubtotal() whenever unitPrice or orderQuantity changes.
    @Column(name = "line_subtotal", precision = 38, scale = 2, nullable = false)
    private BigDecimal lineSubtotal;

    // Recalculates lineSubtotal from current unitPrice and orderQuantity.
    // Call this in the service layer before saving whenever quantity or price changes.
    public void recalcSubtotal() {
        this.lineSubtotal = unitPrice.multiply(BigDecimal.valueOf(orderQuantity));
    }

    // Equality based on business identity (PK), not object reference.
    // Safe for use in JPA collections (Set<BeerOrderLine>) and after proxy unwrapping.
    // Null-safe: transient entities (id == null) are never equal to each other.
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof BeerOrderLine other)) return false;
        return id != null && id.equals(other.id);
    }

    // Fixed hashCode using class — consistent before and after persist (id changes from null to UUID).
    @Override
    public int hashCode() {
        return getClass().hashCode();
    }
}
