package com.restmvc.beer_store.entities;

import com.restmvc.beer_store.enums.DiscountType;
import com.restmvc.beer_store.enums.OrderStatus;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.annotations.UuidGenerator;
import org.hibernate.type.SqlTypes;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.*;

/**
 * Represents a customer's beer order — the aggregate root of the order domain.
 * <p>
 * Relationships:
 * - ManyToOne → Customer: an order always belongs to exactly one customer.
 *   LAZY fetch to avoid loading customer data when working only with the order.
 *   FK is NOT NULL — an order cannot exist without a customer.
 * <p>
 * - ManyToOne → Promotion (nullable): the promotion code applied at checkout, if any.
 *   LAZY fetch — promotion details are rarely needed when processing the order.
 *   Nullable: most orders are placed without a promo code.
 *   No cascade — Promotion is a shared entity managed independently of orders.
 *   IMPORTANT: Deleting a Promotion that has been used on orders is blocked by the FK
 *   constraint. Deactivate promotions instead of deleting them.
 * <p>
 * - OneToMany → BeerOrderLine: an order owns its lines (aggregate root pattern).
 *   CascadeType.ALL + orphanRemoval = true means lines are fully managed through
 *   the order — saving/deleting the order will save/delete all lines automatically.
 *   Use addLine() / removeLine() helpers to keep both sides of the relationship in sync.
 * <p>
 * - OneToOne → BeerOrderShipment: an order may have at most one shipment (1:1).
 *   CascadeType.ALL + orphanRemoval = true — shipment lifecycle is controlled by the order.
 *   LAZY fetch because shipment data is rarely needed alongside order data.
 *   mappedBy = "beerOrder" means BeerOrderShipment holds the FK column (beer_order_id).
 * <p>
 * Indexes:
 * - idx_beer_orders_customer_id: speeds up "all orders for a customer" queries.
 * - idx_beer_orders_created_at: speeds up time-range queries across all orders.
 * - idx_beer_orders_customer_created: composite index for "orders of a customer sorted by date".
 * <p>
 * Discount / Promotion snapshot pattern:
 *   When a promotion is applied, three snapshot fields are copied from Promotion onto the order:
 *     - promoCode:      the code the customer entered (e.g. "SUMMER10")
 *     - promoDiscountType:  PERCENTAGE or FIXED_AMOUNT
 *     - promoDiscountValue: the raw value (e.g. 10.00 for 10% or 5.00 EUR)
 *   These snapshots ensure the order record stays historically accurate even if the
 *   Promotion entity is later modified or deactivated.
 *   discount_amount holds the final computed deduction (calculated by DiscountCalculator
 *   in the service layer, passed into applyPromotionSnapshot()).
 * <p>
 * Amounts: all monetary fields use NUMERIC(38,2) / BigDecimal to avoid floating-point rounding.
 *   total_amount = subtotal - discount + shipping + tax
 *   The service layer is responsible for recalculating and saving all amounts consistently.
 */
@Getter
@Setter
@Builder
@Entity
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "beer_orders",
        indexes = {
                @Index(name = "idx_beer_orders_customer_id", columnList = "customer_id"),
                @Index(name = "idx_beer_orders_created_at", columnList = "created_at"),
                @Index(name = "idx_beer_orders_customer_created", columnList = "customer_id, created_at")
        }
)
@EntityListeners(AuditingEntityListener.class)
public class BeerOrder {

    // UUID primary key — generated by Hibernate's UuidGenerator (random UUID v4).
    // updatable = false prevents accidental PK change after creation.
    @Id
    @GeneratedValue
    @UuidGenerator
    @JdbcTypeCode(SqlTypes.VARCHAR)
    @Column(name = "beer_order_id", updatable = false, nullable = false, columnDefinition = "VARCHAR(36)")
    private UUID id;

    // Optimistic locking — Hibernate auto-increments on every UPDATE.
    // Prevents lost-update anomalies when two transactions modify the same order concurrently.
    // Long (not Integer) to avoid overflow for long-lived, frequently updated orders.
    @Version
    @Column(name = "version")
    private Long version;

    // Populated automatically by Spring Data JPA Auditing (@EntityListeners above).
    // updatable = false ensures the creation timestamp is never overwritten.
    @CreatedDate
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    @LastModifiedDate
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    // LAZY: loading customer data is expensive and not always needed.
    // optional = false mirrors the DB NOT NULL constraint — every order must have a customer.
    // No CascadeType here — customer lifecycle is independent of order lifecycle.
    @ManyToOne(optional = false, fetch = FetchType.LAZY)
    @JoinColumn(name = "customer_id", nullable = false)
    private Customer customer;

    // Stored as VARCHAR using the enum name (EnumType.STRING).
    // Preferred over EnumType.ORDINAL — adding/reordering enum values won't corrupt DB data.
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    private OrderStatus status;

    // ISO 4217 currency code (e.g. "EUR", "USD"). Stored per order so pricing
    // remains correct even if the system's default currency changes later.
    @Column(name = "currency", nullable = false, length = 3)
    private String currency;

    // -------------------------------------------------------------------------
    // Promotion (optional) — nullable FK + snapshot fields
    // -------------------------------------------------------------------------

    // Live reference to the Promotion entity for reporting / admin queries.
    // Nullable: most orders are placed without a promo code.
    // LAZY: promotion details are not needed for the vast majority of order processing.
    // No cascade — Promotion is a shared entity; deleting an order must NOT affect the promotion.
    // To remove historical data risk: deactivate Promotions, never delete used ones.
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "promotion_id", nullable = true)
    private Promotion promotion;

    // Snapshot of the promo code entered by the customer at checkout (e.g. "SUMMER10").
    // Preserved here so the order record stays accurate even if Promotion.code is changed later.
    // Null when no promotion was applied.
    @Column(name = "promo_code", length = 50)
    private String promoCode;

    // Snapshot of how the discount was calculated (PERCENTAGE or FIXED_AMOUNT).
    // Stored so order receipts and refund logic don't need to re-fetch the Promotion entity.
    // Null when no promotion was applied.
    @Enumerated(EnumType.STRING)
    @Column(name = "promo_discount_type", length = 20)
    private DiscountType promoDiscountType;

    // Snapshot of the raw discount value at the time of order placement.
    // Example: 10.00 (meaning 10% or 10 EUR depending on promoDiscountType).
    // Null when no promotion was applied.
    @Column(name = "promo_discount_value", precision = 38, scale = 2)
    private BigDecimal promoDiscountValue;

    // -------------------------------------------------------------------------
    // Financial amounts (all snapshots at order creation time)
    // -------------------------------------------------------------------------

    // Sum of all BeerOrderLine.lineSubtotal values before any deductions.
    @Column(name = "subtotal_amount", precision = 38, scale = 2, nullable = false)
    private BigDecimal subtotalAmount;

    // The computed discount deducted from subtotalAmount.
    // = Promotion.calculateDiscountAmount(subtotalAmount), or ZERO if no promotion.
    // Stored so receipts and refunds always show the exact amount that was deducted.
    @Column(name = "discount_amount", precision = 38, scale = 2, nullable = false)
    private BigDecimal discountAmount;

    @Column(name = "shipping_amount", precision = 38, scale = 2, nullable = false)
    private BigDecimal shippingAmount;

    @Column(name = "tax_amount", precision = 38, scale = 2, nullable = false)
    private BigDecimal taxAmount;

    // total_amount = subtotal - discount + shipping + tax
    // Stored (denormalized) to avoid recalculation on every read and to preserve
    // the exact total the customer was charged, even if pricing rules change later.
    @Column(name = "total_amount", precision = 38, scale = 2, nullable = false)
    private BigDecimal totalAmount;

    // -------------------------------------------------------------------------
    // Collections
    // -------------------------------------------------------------------------

    // CascadeType.ALL: all JPA operations (persist, merge, remove) propagate to lines.
    // orphanRemoval = true: removing a line from this Set will delete it from the DB.
    // Together they implement the "aggregate root controls children" pattern.
    // @Builder.Default so Lombok builder initializes the set (avoids NPE when using builder).
    @OneToMany(mappedBy = "beerOrder", cascade = CascadeType.ALL, orphanRemoval = true)
    @Builder.Default
    private Set<BeerOrderLine> lines = new LinkedHashSet<>();

    // OneToOne — each order has at most one shipment.
    // CascadeType.ALL + orphanRemoval = true: shipment is created/deleted through the order.
    // LAZY fetch — shipment is rarely needed when loading the order for processing.
    // mappedBy = "beerOrder" means BeerOrderShipment owns the FK column (beer_order_id UNIQUE).
    @OneToOne(mappedBy = "beerOrder", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
    private BeerOrderShipment shipment;

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    // Helper to keep both sides of the bidirectional OneToMany in sync.
    // Always use this instead of lines.add(line) directly.
    public void addLine(BeerOrderLine line) {
        line.setBeerOrder(this);
        this.lines.add(line);
    }

    // Helper to keep both sides in sync on removal.
    // Setting beerOrder to null on the line triggers orphanRemoval to delete it from DB.
    public void removeLine(BeerOrderLine line) {
        this.lines.remove(line);
        line.setBeerOrder(null);
    }

    /**
     * Stores a promotion snapshot on this order.
     *
     * <p>This method is a pure setter — it copies already-validated and already-calculated
     * values onto the order. All business logic must be performed BEFORE calling this by
     * the service layer in the following order:
     * <ol>
     *   <li>{@code PromotionValidator.validate(promo, now)}                    — check active, dates, uses.</li>
     *   <li>{@code DiscountCalculator.calculate(type, value, subtotal)}        — compute discountAmount.</li>
     *   <li>{@code order.applyPromotionSnapshot(promo, discountAmount)}        — store snapshot here.</li>
     *   <li>{@code order.recalculateTotals()}                                  — update total_amount.</li>
     *   <li>{@code promo.setUsedCount(promo.getUsedCount() + 1)}; save promo  — track usage.</li>
     * </ol>
     * </p>
     *
     * @param promo          the validated Promotion entity (must not be null)
     * @param discountAmount the pre-calculated discount to deduct (must be &gt;= 0)
     */
    public void applyPromotionSnapshot(Promotion promo, BigDecimal discountAmount) {
        this.promotion = promo;
        this.promoCode = promo.getCode();
        this.promoDiscountType = promo.getDiscountType();
        this.promoDiscountValue = promo.getDiscountValue();
        this.discountAmount = discountAmount;
    }

    /**
     * Removes any applied promotion from this order and resets discount to zero.
     * Caller must still invoke recalculateTotals() after this to update total_amount.
     */
    public void removePromotion() {
        this.promotion = null;
        this.promoCode = null;
        this.promoDiscountType = null;
        this.promoDiscountValue = null;
        this.discountAmount = BigDecimal.ZERO;
    }

    /**
     * Recalculates and sets total_amount based on current field values.
     * Formula: total = subtotal - discount + shipping + tax
     * Call this after any change to subtotal, discount, shipping, or tax.
     */
    public void recalculateTotals() {
        this.totalAmount = this.subtotalAmount
                .subtract(this.discountAmount)
                .add(this.shippingAmount)
                .add(this.taxAmount);
    }

    // Equality based on business identity (PK), not object reference.
    // Safe for use in JPA collections and after detach/proxy unwrapping.
    // Null-safe: transient (not-yet-persisted) entities are never equal to each other.
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof BeerOrder other)) return false;
        return id != null && id.equals(other.id);
    }

    // Fixed hashCode using class — consistent before and after persist (id changes from null to UUID).
    // Required contract: objects that are equal must have the same hashCode.
    @Override
    public int hashCode() {
        return getClass().hashCode();
    }
}
