package com.restmvc.beer_store.entities;

import com.restmvc.beer_store.enums.ShipmentStatus;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.UuidGenerator;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Represents a shipment associated with a BeerOrder.
 * Each order can have at most one shipment (1:1 relationship).
 * <p>
 * Relationships:
 * - OneToOne → BeerOrder: this entity owns the FK column (beer_order_id).
 * "Owning side" = this class has @JoinColumn, BeerOrder has mappedBy.
 * LAZY fetch: when loading a shipment, we rarely need the full order.
 * optional = false + nullable = false: a shipment must always reference an order.
 * unique = true on the FK column enforces the 1:1 constraint at the DB level.
 * ON DELETE CASCADE in SQL: if the order is deleted, the shipment is deleted too.
 * JPA cascade is handled from the BeerOrder side (CascadeType.ALL + orphanRemoval).
 * <p>
 * Why BeerOrderShipment owns the FK (not BeerOrder)?
 * Shipment is an optional child — not every order has a shipment yet.
 * Placing the FK on the shipment table avoids a nullable beer_order_shipment_id column
 * in the beer_orders table, keeping the schema cleaner.
 * <p>
 * Status flow: NEW → SENT → IN_TRANSIT → DELIVERED
 * Enforced by a CHECK constraint in the DB (chk_shipment_status) and by the ShipmentStatus enum.
 */
@Getter
@Setter
@Builder
@Entity
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "beer_order_shipments",
        indexes = {
                // Speeds up tracking number lookups (e.g. customer tracking page, courier webhook).
                @Index(name = "idx_bos_tracking_number", columnList = "tracking_number")
        }
)
@EntityListeners(AuditingEntityListener.class)
public class BeerOrderShipment {

    // UUID primary key — generated by Hibernate's UuidGenerator (random UUID v4).
    // updatable = false prevents accidental PK change after creation.
    @Id
    @GeneratedValue
    @UuidGenerator
    @Column(name = "beer_order_shipment_id", updatable = false, nullable = false, columnDefinition = "VARCHAR(36)")
    private UUID id;

    // Optimistic locking — prevents concurrent status updates on the same shipment.
    // Long (not Integer) to avoid overflow for long-lived entities.
    @Version
    @Column(name = "version")
    private Long version;

    // Managed automatically by Spring Data JPA Auditing.
    // updatable = false ensures created_at is never overwritten after first insert.
    @CreatedDate
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    @LastModifiedDate
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    // This side OWNS the FK column (beer_order_id) — the "owning side" of the 1:1.
    // unique = true enforces one-shipment-per-order at the DB level.
    // LAZY fetch — the full order is rarely needed when processing shipment status updates.
    // optional = false: a shipment must always be linked to an order.
    @OneToOne(optional = false, fetch = FetchType.LAZY)
    @JoinColumn(name = "beer_order_id", nullable = false, unique = true)
    private BeerOrder beerOrder;

    // Reference to the Address used as the delivery destination at checkout time.
    // Nullable: a shipment may be created before an address is assigned, or the
    //           address may have been soft-deleted (isActive = false) — the FK is preserved.
    // LAZY: address details are only needed when displaying shipment info.
    // No cascade: Address lifecycle is managed through Customer, not through Shipment.
    // IMPORTANT: Address uses soft delete — never hard-delete an Address that has shipments.
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "address_id", nullable = true)
    private Address address;

    // External carrier tracking number (e.g. "1Z999AA10123456784").
    // Nullable: assigned by the shipping service after the shipment is created.
    @Column(name = "tracking_number", length = 50)
    private String trackingNumber;

    // Current status in the shipment lifecycle: NEW → SENT → IN_TRANSIT → DELIVERED.
    // EnumType.STRING: stored as the enum constant name — safe against enum reordering.
    // DB CHECK constraint (chk_shipment_status) provides an additional guard.
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    private ShipmentStatus status;
}
