package com.restmvc.beer_store.entities;

import com.restmvc.beer_store.enums.CartStatus;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.annotations.UuidGenerator;
import org.hibernate.type.SqlTypes;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.LocalDateTime;
import java.util.*;

/**
 * Represents a shopping cart belonging to a customer.
 * A cart is a temporary container for beers before the customer places an order.
 * When checkout is completed, the cart transitions to CHECKED_OUT and a BeerOrder is created.
 * <p>
 * Status lifecycle: ACTIVE → CHECKED_OUT (on successful order placement)
 * ACTIVE → ABANDONED  (on expiry / manual abandonment)
 * <p>
 * Relationships:
 * - ManyToOne → Customer: a cart always belongs to exactly one customer.
 * LAZY fetch — customer details are rarely needed when working with cart contents.
 * optional = false + nullable = false: a cart cannot exist without a customer.
 * ON DELETE CASCADE in SQL: if a customer is deleted, their carts are deleted too.
 * No cascade here — customer lifecycle is managed independently.
 * <p>
 * - OneToMany → CartItem: a cart owns its items (aggregate root pattern).
 * CascadeType.ALL + orphanRemoval = true: items are fully managed through the cart.
 * Use addItem() / removeItem() helpers to keep both sides of the relationship in sync.
 *
 * @Builder.Default initializes the Set so Lombok builder does not leave it null.
 * <p>
 * Uniqueness:
 * A customer can have at most ONE ACTIVE cart at a time — enforced by a partial unique index
 * in the DB (uk_carts_customer_active). Historical carts (CHECKED_OUT, ABANDONED) are retained
 * for audit purposes and are not affected by the uniqueness constraint.
 * <p>
 * Index:
 * - idx_carts_customer_id: speeds up "find all carts for a customer" queries.
 */
@Getter
@Setter
@Builder
@Entity
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "carts",
        indexes = {
                // Speeds up "all carts for a customer" queries (active + history lookups).
                @Index(name = "idx_carts_customer_id", columnList = "customer_id")
        }
)
@EntityListeners(AuditingEntityListener.class)
public class Cart {

    // UUID primary key — generated by Hibernate's UuidGenerator (random UUID v4).
    // updatable = false prevents accidental PK change after creation.
    @Id
    @UuidGenerator
    @JdbcTypeCode(SqlTypes.VARCHAR)
    @Column(name = "cart_id", updatable = false, nullable = false, columnDefinition = "VARCHAR(36)")
    private UUID id;

    // Optimistic locking — prevents concurrent modification of the same cart
    // (e.g. two browser tabs adding items simultaneously).
    // Long (not Integer) for consistency with other entities and to avoid overflow.
    @Version
    @Column(name = "version")
    private Long version;

    // Managed automatically by Spring Data JPA Auditing.
    // updatable = false ensures created_at is never overwritten after first insert.
    @CreatedDate
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    @LastModifiedDate
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    // LAZY — customer data is not needed for the vast majority of cart operations.
    // optional = false mirrors the DB NOT NULL constraint.
    // No cascade — customer lifecycle is independent of cart lifecycle.
    @ManyToOne(optional = false, fetch = FetchType.LAZY)
    @JoinColumn(name = "customer_id", nullable = false)
    private Customer customer;

    // Current state of the cart. EnumType.STRING: stored as enum name, safe against reordering.
    // DB CHECK constraint (chk_carts_status) provides an additional guard.
    // Lifecycle: ACTIVE → CHECKED_OUT | ABANDONED
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    private CartStatus status;

    // ISO 4217 currency code (e.g. "EUR", "USD"). Stored per order so pricing
    // remains correct even if the system's default currency changes later.
    @Column(name = "currency", nullable = false, length = 3)
    private String currency;

    // CascadeType.ALL: persist/merge/remove propagate to all items.
    // orphanRemoval = true: removing an item from this Set deletes it from the DB.
    // @Builder.Default: Lombok builder initializes the set (avoids NPE when using builder pattern).
    @OneToMany(mappedBy = "cart", cascade = CascadeType.ALL, orphanRemoval = true)
    @Builder.Default
    private Set<CartItem> items = new LinkedHashSet<>();

    // Helper to keep both sides of the bidirectional OneToMany in sync.
    // Always use this instead of items.add(item) directly.
    public void addItem(CartItem item) {
        item.setCart(this);
        this.items.add(item);
    }

    // Helper to keep both sides in sync on removal.
    // Setting cart to null on the item triggers orphanRemoval to delete it from the DB.
    public void removeItem(CartItem item) {
        this.items.remove(item);
        item.setCart(null);
    }

    // Equality based on business identity (PK), not object reference.
    // Safe for use in JPA collections and after detach/proxy unwrapping.
    // Null-safe: transient (not-yet-persisted) entities are never equal to each other.
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Cart other)) return false;
        return id != null && id.equals(other.id);
    }

    // Fixed hashCode using class — consistent before and after persist (id changes from null to UUID).
    @Override
    public int hashCode() {
        return getClass().hashCode();
    }
}
