package com.restmvc.beer_store.entities;

import jakarta.persistence.*;
import jakarta.validation.constraints.Positive;
import lombok.*;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.annotations.UuidGenerator;
import org.hibernate.type.SqlTypes;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Represents a single line item inside a Cart.
 * Each CartItem links one Beer to one Cart with a desired quantity.
 * <p>
 * A given beer can appear at most once per cart (enforced by uk_cart_items_cart_beer).
 * If the user adds the same beer again, the service layer should increment quantity on the
 * existing CartItem rather than inserting a new one.
 * <p>
 * Relationships:
 * - ManyToOne → Cart: many items belong to one cart (the parent aggregate root).
 * LAZY fetch — cart data is usually already loaded in the persistence context.
 * optional = false + nullable = false: an item cannot exist without a cart.
 * ON DELETE CASCADE in SQL: deleting a cart removes all its items at the DB level.
 * JPA cascade is managed from the Cart side (CascadeType.ALL + orphanRemoval).
 * <p>
 * - ManyToOne → Beer: references the beer catalog.
 * LAZY fetch — beer details are not always needed when processing cart operations.
 * optional = false: every item must reference a valid, existing beer.
 * No cascade — Beer is a shared catalog entity; deleting a cart item must NOT delete the beer.
 * Deleting a Beer that is in an active cart would violate the FK constraint (intentional guard).
 * <p>
 * Quantity:
 * Must be >= 1. Zero-quantity items should be removed from the cart entirely, not kept at 0.
 * Enforced at three layers:
 * 1. Bean validation: @Positive (triggers before DB insert/update).
 * 2. DB CHECK constraint: chk_cart_items_qty (quantity > 0).
 * 3. Service layer: should enforce business rules (max quantity per item, stock limits).
 * <p>
 * Note: CartItem does NOT store a price snapshot (unlike BeerOrderLine).
 * The cart is a pre-order stage — the final price is calculated at checkout time
 * from the beer's current price. Price snapshots are stored on BeerOrderLine instead.
 */
@Getter
@Setter
@Builder
@Entity
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "cart_items",
        uniqueConstraints = {
                // One beer per cart — prevents duplicate rows for the same beer.
                // Service layer must increment quantity on the existing item instead of inserting.
                @UniqueConstraint(name = "uk_cart_items_cart_beer", columnNames = {"cart_id", "beer_id"})
        },
        indexes = {
                // Speeds up "all items in a cart" queries (used on every cart load).
                @Index(name = "idx_cart_items_cart_id", columnList = "cart_id"),
                // Speeds up "which carts contain this beer" queries (stock checks, beer deletion guards).
                @Index(name = "idx_cart_items_beer_id", columnList = "beer_id")
        }
)
@EntityListeners(AuditingEntityListener.class)
public class CartItem {

    // UUID primary key — generated by Hibernate's UuidGenerator (random UUID v4).
    // updatable = false prevents accidental PK change after creation.
    @Id
    @UuidGenerator
    @JdbcTypeCode(SqlTypes.VARCHAR)
    @Column(name = "cart_item_id", updatable = false, nullable = false, columnDefinition = "VARCHAR(36)")
    private UUID id;

    // Optimistic locking — prevents concurrent quantity updates on the same cart item.
    // Long (not Integer) for consistency with other entities and to avoid overflow.
    @Version
    @Column(name = "version")
    private Long version;

    // Managed automatically by Spring Data JPA Auditing.
    // updatable = false ensures created_at is never overwritten after first insert.
    @CreatedDate
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    @LastModifiedDate
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    // Parent cart — LAZY because we usually work with items in the context of a loaded cart,
    // so the cart is already in the persistence context (no extra query needed).
    // optional = false enforces NOT NULL at the JPA level (mirrors DB constraint).
    @ManyToOne(optional = false, fetch = FetchType.LAZY)
    @JoinColumn(name = "cart_id", nullable = false)
    private Cart cart;

    // Reference to the beer catalog. LAZY — beer details are not always needed.
    // No cascade: Beer is a shared entity — deleting a cart item must NOT delete the beer.
    // optional = false: every cart item must reference an existing beer.
    @ManyToOne(optional = false, fetch = FetchType.LAZY)
    @JoinColumn(name = "beer_id", nullable = false)
    private Beer beer;

    // Desired quantity of this beer in the cart. Must be at least 1.
    // @Positive runs as bean validation before any DB interaction.
    // DB CHECK constraint (chk_cart_items_qty) provides an additional safety net.
    // When the user removes all units, remove the CartItem entirely via Cart.removeItem().
    @Positive
    @Column(name = "quantity", nullable = false)
    private Integer quantity;

    // Equality based on business identity (PK), not object reference.
    // Safe for use in JPA collections (Set<CartItem>) and after proxy unwrapping.
    // Null-safe: transient (not-yet-persisted) entities are never equal to each other.
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof CartItem other)) return false;
        return id != null && id.equals(other.id);
    }

    // Fixed hashCode using class — consistent before and after persist (id changes from null to UUID).
    @Override
    public int hashCode() {
        return getClass().hashCode();
    }
}
