package com.restmvc.beer_store.entities;

import com.restmvc.beer_store.enums.DiscountType;
import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.*;
import org.hibernate.annotations.UuidGenerator;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

/**
 * JPA entity representing a promotional discount code.
 * <p>
 * This entity is a pure data object — it holds promotion configuration only.
 * All business logic is delegated to dedicated service-layer components:
 * <ul>
 *   <li>{@code PromotionValidator} — validates whether this promotion can be applied right now.</li>
 *   <li>{@code DiscountCalculator}  — computes the monetary discount amount from type + value.</li>
 *   <li>{@code CartService}         — orchestrates validation, calculation, snapshot, and use tracking.</li>
 * </ul>
 * <p>
 * Lifecycle (managed externally by CartService / OrderService):
 * <ol>
 *   <li>Admin creates a Promotion with a unique code, type, value, and optional limits.</li>
 *   <li>Customer enters the code at checkout.</li>
 *   <li>PromotionValidator checks active flag, date range, and max_uses.</li>
 *   <li>DiscountCalculator computes the discount amount from subtotal.</li>
 *   <li>CartService stores a snapshot of (code, type, value, amount) on the BeerOrder.</li>
 *   <li>CartService increments used_count and saves both entities in one transaction.</li>
 * </ol>
 * <p>
 * Snapshot pattern:
 * When a promotion is applied to an order, the relevant fields (code, type, value) are
 * copied onto BeerOrder. Future edits or deactivation of this entity do NOT affect
 * historical orders — the audit trail is fully preserved on the order side.
 * <p>
 * Relationships:
 * - OneToMany → BeerOrder (via BeerOrder.promotion FK): one promotion can be applied to many orders.
 *   No cascade — Promotion lifecycle is independent of orders.
 *   Deleting a Promotion that has been used on orders is blocked by the FK constraint.
 *   Always deactivate (active = false) instead of deleting.
 */
@Getter
@Setter
@Builder
@Entity
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "promotions",
        indexes = {
                // Primary lookup path: customer enters a code → find promotion by code.
                @Index(name = "idx_promotions_code", columnList = "code"),
                // Admin queries: "show all currently active promotions in a date range".
                @Index(name = "idx_promotions_active_valid", columnList = "active, valid_from, valid_until")
        }
)
@EntityListeners(AuditingEntityListener.class)
public class Promotion {

    // UUID primary key — generated by Hibernate's UuidGenerator (random UUID v4).
    // updatable = false prevents accidental PK change after creation.
    @Id
    @GeneratedValue
    @UuidGenerator
    @Column(name = "promotion_id", updatable = false, nullable = false, columnDefinition = "varchar(36)")
    private UUID id;

    // Optimistic locking — prevents concurrent used_count increments from losing data.
    // Long (not Integer) for consistency with other entities and to avoid overflow.
    @Version
    @Column(name = "version")
    private Long version;

    // Managed automatically by Spring Data JPA Auditing.
    @CreatedDate
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    @LastModifiedDate
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    // Human-readable promo code entered by the customer (e.g. "SUMMER10", "WELCOME5").
    // Always stored and compared uppercase — CartService must normalise input before lookup.
    // Unique: two promotions cannot share the same code.
    @NotBlank
    @Size(min = 2, max = 50)
    @Column(name = "code", length = 50, nullable = false, unique = true)
    private String code;

    // Optional human-readable label for admin UI (e.g. "Summer sale 2026").
    @Size(max = 100)
    @Column(name = "description", length = 100)
    private String description;

    // How the discount value is applied — determines DiscountCalculator's formula.
    // PERCENTAGE: value = 10.00 → 10% off subtotal.
    // FIXED_AMOUNT: value = 5.00 → 5 EUR off subtotal.
    // EnumType.STRING: safe against enum constant reordering in the future.
    @Enumerated(EnumType.STRING)
    @Column(name = "discount_type", nullable = false, length = 20)
    private DiscountType discountType;

    // The magnitude of the discount — interpreted by DiscountCalculator based on discountType.
    // Bean validation enforces > 0; DB CHECK constraint (chk_promotions_value) is a second guard.
    // For PERCENTAGE: PromotionValidator additionally ensures this is <= 100.
    @NotNull
    @DecimalMin(value = "0.01")
    @Column(name = "discount_value", precision = 38, scale = 2, nullable = false)
    private BigDecimal discountValue;

    // Maximum total number of times this promotion can be used across all orders.
    // null = unlimited uses. Checked by PromotionValidator before applying.
    @Column(name = "max_uses")
    private Integer maxUses;

    // Running counter of how many orders have successfully applied this promotion.
    // Incremented by CartService (or OrderService) inside the checkout transaction.
    // Protected against concurrent double-use by @Version (optimistic locking).
    @Column(name = "used_count", nullable = false)
    @Builder.Default
    private Integer usedCount = 0;

    // Start of validity window (inclusive). null = valid from creation.
    // Checked by PromotionValidator.
    @Column(name = "valid_from")
    private LocalDateTime validFrom;

    // End of validity window (inclusive). null = never expires.
    // Checked by PromotionValidator.
    @Column(name = "valid_until")
    private LocalDateTime validUntil;

    // Master on/off switch.
    // Always set active = false instead of deleting — deletion would violate FK constraints
    // on orders that have already used this promotion.
    @Column(name = "active", nullable = false)
    @Builder.Default
    private Boolean active = true;

    // Equality based on business identity (PK), not object reference.
    // Safe for use in JPA collections and after detach/proxy unwrapping.
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Promotion other)) return false;
        return id != null && id.equals(other.id);
    }

    // Fixed hashCode using class — consistent before and after persist (id changes from null to UUID).
    @Override
    public int hashCode() {
        return getClass().hashCode();
    }
}
