package com.restmvc.beer_store.mappers;

import com.restmvc.beer_store.dtos.beer.BeerCreateRequestDTO;
import com.restmvc.beer_store.dtos.beer.BeerResponseDTO;
import com.restmvc.beer_store.dtos.beer.BeerUpdateRequestDTO;
import com.restmvc.beer_store.entities.Beer;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;

/**
 * MapStruct mapper responsible for converting between
 * {@link BeerCreateRequestDTO} and {@link Beer} entity.
 *
 * <p>This mapper is used to transform incoming API request data
 * into a persistable domain entity. It intentionally ignores
 * persistence-managed fields such as identifiers, versioning,
 * timestamps, and relationships.</p>
 *
 * <p>Mapping rules:</p>
 * <ul>
 *     <li>Entity ID is generated by the persistence layer</li>
 *     <li>Version field is managed by optimistic locking</li>
 *     <li>Timestamps are handled via JPA auditing</li>
 *     <li>Categories are assigned separately in the service layer</li>
 * </ul>
 */
@Mapper
public interface BeerMapper {

    /**
     * Maps a {@link BeerCreateRequestDTO} to a new {@link Beer} entity instance.
     *
     * <p>The resulting entity has not yet persisted and does not contain
     * generated identifiers or auditing fields.</p>
     *
     * @param beerCreateRequestDTO DTO containing data required to create a Beer
     * @return new {@link Beer} entity instance
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "version", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    @Mapping(target = "categories", ignore = true)
    Beer dtoToBeer(BeerCreateRequestDTO beerCreateRequestDTO);

    /**
     * Maps a {@link Beer} entity to a {@link BeerResponseDTO}.
     *
     * <p>This method is used to transform a Beer entity into a DTO suitable
     * for API responses. It excludes sensitive or unnecessary fields.</p>
     *
     * @param beer Beer entity to be converted
     * @return DTO representing the Beer entity
     */
    BeerResponseDTO beerToResponseDto(Beer beer);

    /**
     * Updates a {@link Beer} entity from a {@link BeerUpdateRequestDTO}.
     * <p>
     *     Updates a Beer entity with data from a BeerUpdateRequestDTO.
     *     Excludes fields that should not be updated, such as ID, version, createdAt, updatedAt, and categories.
     * </p>
     * @param beer Beer entity to be updated
     * @param beerUpdateRequestDTO data to update the Beer entity with
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "version", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    void updateBeerFromDto(BeerUpdateRequestDTO beerUpdateRequestDTO, @MappingTarget Beer beer);
}