package com.restmvc.beer_store.mappers;

import com.restmvc.beer_store.dtos.beer.*;
import com.restmvc.beer_store.dtos.beerCategory.BeerListItemDTO;
import com.restmvc.beer_store.entities.Beer;
import org.mapstruct.*;

/**
 * MapStruct mapper responsible for converting between
 * {@link BeerCreateRequestDTO} and {@link Beer} entity.
 *
 * <p>This mapper is used to transform incoming API request data
 * into a persistable domain entity. It intentionally ignores
 * persistence-managed fields such as identifiers, versioning,
 * timestamps, and relationships.</p>
 *
 * <p>Mapping rules:</p>
 * <ul>
 *     <li>Entity ID is generated by the persistence layer</li>
 *     <li>Version field is managed by optimistic locking</li>
 *     <li>Timestamps are handled via JPA auditing</li>
 *     <li>Categories are assigned separately in the service layer</li>
 * </ul>
 */
@Mapper
public interface BeerMapper {

    /**
     * Maps a {@link BeerCreateRequestDTO} to a new {@link Beer} entity instance.
     *
     * @param beerCreateRequestDTO DTO containing data required to create a Beer
     * @return new {@link Beer} entity instance
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "version", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    @Mapping(target = "categories", ignore = true)
    Beer dtoToBeer(BeerCreateRequestDTO beerCreateRequestDTO);

    /**
     * Maps a {@link Beer} entity to a {@link BeerResponseDTO}.
     *
     * @param beer Beer entity to be converted
     * @return DTO representing the Beer entity
     */
    BeerResponseDTO beerToResponseDto(Beer beer);

    /**
     * Updates a {@link Beer} entity from a {@link BeerUpdateRequestDTO}.
     *
     * @param beer Beer entity to be updated
     * @param beerUpdateRequestDTO data to update the Beer entity with
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "version", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    void updateBeerFromDto(BeerUpdateRequestDTO beerUpdateRequestDTO, @MappingTarget Beer beer);

    /**
     * Patches a {@link Beer} entity from a {@link BeerPatchRequestDTO}.
     *
     * @param beerPatchRequestDTO DTO containing data to patch the Beer entity with
     * @param beer Beer entity to be patched
     */
    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "version", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    @Mapping(target = "categories", ignore = true)
    void patchBeerFromDto(BeerPatchRequestDTO beerPatchRequestDTO, @MappingTarget Beer beer);

    /**
     * Converts a {@link Beer} entity to a {@link BeerListItemDTO}.
     *
     * @param beer Beer entity to be converted
     * @return {@link BeerListItemDTO} representing the Beer entity
     */
    BeerListItemDTO beerToBeerListItemDto(Beer beer);
}