package com.restmvc.beer_store.mappers;

import com.restmvc.beer_store.dtos.cart.CartItemResponseDTO;
import com.restmvc.beer_store.dtos.cart.CartResponseDTO;
import com.restmvc.beer_store.dtos.cart.CreateCartRequestDTO;
import com.restmvc.beer_store.entities.Cart;
import com.restmvc.beer_store.entities.CartItem;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import java.math.BigDecimal;
import java.util.List;
import java.util.Set;

/**
 * MapStruct mapper for converting between {@link Cart} / {@link CartItem} entities
 * and their corresponding DTOs.
 *
 * <p>Mapping summary:
 * <ul>
 *   <li>{@link #dtoToCart}               — CreateCartRequestDTO → new Cart entity</li>
 *   <li>{@link #entityToCartResponseDTO} — Cart entity → full CartResponseDTO (with items + total)</li>
 *   <li>{@link #cartItemToResponse}      — CartItem entity → CartItemResponseDTO</li>
 * </ul>
 * </p>
 */
@Mapper
public interface CartMapper {

    /**
     * Maps a create-cart request DTO to a new {@link Cart} entity.
     *
     * <p>Fields ignored here are set by the service layer or JPA/Hibernate:
     * <ul>
     *   <li>{@code id}        — generated by @UuidGenerator on first persist</li>
     *   <li>{@code version}   — managed by Hibernate optimistic locking</li>
     *   <li>{@code createdAt} / {@code updatedAt} — set by Spring Data JPA Auditing</li>
     *   <li>{@code items}     — cart starts empty; items are added via addItem()</li>
     *   <li>{@code customer}  — set explicitly in CartService after loading the Customer</li>
     *   <li>{@code status}    — always set to ACTIVE on creation by CartService</li>
     * </ul>
     * </p>
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "version", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    @Mapping(target = "items", ignore = true)
    @Mapping(target = "customer", ignore = true)
    @Mapping(target = "status", ignore = true)
    Cart dtoToCart(CreateCartRequestDTO createCartRequestDTO);

    /**
     * Maps a {@link Cart} entity to a full {@link CartResponseDTO}.
     *
     * <p>Field mappings:
     * <ul>
     *   <li>{@code cartId}     ← {@code cart.id}</li>
     *   <li>{@code customerId} ← {@code cart.customer.id} (requires customer to be loaded)</li>
     *   <li>{@code status}     ← {@code cart.status.name()} (enum → String for API stability)</li>
     *   <li>{@code items}      ← mapped via {@link #cartItemsToResponse}</li>
     *   <li>{@code cartTotal}  ← computed via {@link #computeCartTotal}</li>
     * </ul>
     * </p>
     *
     * <p>Must be called inside an active transaction — {@code cart.items} is LAZY.</p>
     */
    @Mapping(target = "cartId", source = "id")
    @Mapping(target = "customerId", source = "customer.id")
    @Mapping(target = "status", expression = "java(cart.getStatus().name())")
    @Mapping(target = "items", expression = "java(cartItemsToResponse(cart.getItems()))")
    @Mapping(target = "cartTotal", expression = "java(computeCartTotal(cart.getItems()))")
    CartResponseDTO entityToCartResponseDTO(Cart cart);

    /**
     * Maps a single {@link CartItem} to a {@link CartItemResponseDTO}.
     *
     * <p>Field mappings:
     * <ul>
     *   <li>{@code cartItemId} ← {@code item.id}</li>
     *   <li>{@code beerId}     ← {@code item.beer.id}</li>
     *   <li>{@code beerName}   ← {@code item.beer.beerName}</li>
     *   <li>{@code unitPrice}  ← {@code item.beer.price} (current catalog price, NOT a snapshot)</li>
     *   <li>{@code lineTotal}  ← computed: {@code unitPrice * quantity}</li>
     * </ul>
     * </p>
     */
    @Mapping(target = "cartItemId", source = "id")
    @Mapping(target = "beerId", source = "beer.id")
    @Mapping(target = "beerName", source = "beer.beerName")
    @Mapping(target = "unitPrice", source = "beer.price")
    @Mapping(target = "lineTotal",
            expression = "java(item.getBeer().getPrice().multiply(java.math.BigDecimal.valueOf(item.getQuantity())))")
    CartItemResponseDTO cartItemToResponse(CartItem item);

    // -------------------------------------------------------------------------
    // Default helper methods — called from @Mapping expressions above
    // -------------------------------------------------------------------------

    /**
     * Converts a Set of CartItem entities to an ordered List of DTOs.
     * Returns an empty list if the set is null (e.g. newly created cart before flush).
     */
    default List<CartItemResponseDTO> cartItemsToResponse(Set<CartItem> items) {
        if (items == null) return List.of();
        return items.stream()
                .map(this::cartItemToResponse)
                .toList();
    }

    /**
     * Computes the cart subtotal as the sum of all line totals (unitPrice * quantity).
     * Returns ZERO for an empty or null items set.
     *
     * <p>This is a convenience value — it does NOT include discount, shipping, or tax.
     * Those are computed at checkout when the cart is converted to a BeerOrder.</p>
     */
    default BigDecimal computeCartTotal(Set<CartItem> items) {
        if (items == null || items.isEmpty()) return BigDecimal.ZERO;
        return items.stream()
                .map(item -> item.getBeer().getPrice()
                        .multiply(BigDecimal.valueOf(item.getQuantity())))
                .reduce(BigDecimal.ZERO, BigDecimal::add);
    }
}
