package com.restmvc.beer_store.mappers;

import com.restmvc.beer_store.dtos.category.CategoryCreateRequestDTO;
import com.restmvc.beer_store.dtos.category.CategoryResponseDTO;
import com.restmvc.beer_store.entities.Category;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;

/**
 * MapStruct mapper responsible for converting between {@link Category} entity
 * and its corresponding DTOs.
 *
 * <p>Mapping rules:</p>
 * <ul>
 *     <li>Entity ID is generated by the persistence layer and must not be overwritten on update</li>
 *     <li>Version field is managed by optimistic locking</li>
 *     <li>Timestamps are handled via JPA auditing</li>
 * </ul>
 */
@Mapper
public interface CategoryMapper {

    /**
     * Maps a {@link Category} entity to a {@link CategoryResponseDTO}.
     *
     * @param category the category entity to convert
     * @return {@link CategoryResponseDTO} representing the category
     */
    CategoryResponseDTO categoryToResponseDto(Category category);

    /**
     * Maps a {@link CategoryCreateRequestDTO} to a new {@link Category} entity.
     *
     * @param dto DTO containing data required to create a category
     * @return new {@link Category} entity instance
     */
    Category dtoToCategory(CategoryCreateRequestDTO dto);

    /**
     * Updates an existing {@link Category} entity from a {@link CategoryCreateRequestDTO}.
     *
     * <p>Persistence-managed fields (id, version, timestamps) are intentionally ignored
     * to prevent accidental overwriting.</p>
     *
     * @param dto      DTO containing the new category data
     * @param category the existing category entity to update
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "version", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    void updateCategoryFromDto(CategoryCreateRequestDTO dto, @MappingTarget Category category);
}
