package com.restmvc.beer_store.mappers;

import com.restmvc.beer_store.dtos.customer.CustomerCreateRequestDTO;
import com.restmvc.beer_store.dtos.customer.CustomerResponseDTO;
import com.restmvc.beer_store.entities.Customer;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;

/**
 * MapStruct mapper for converting between {@link Customer} entities and their DTOs.
 *
 * <p>MapStruct generates a Spring bean implementation at compile time based on the method
 * signatures and {@code @Mapping} annotations. The generated class is injected via
 * Spring's dependency injection wherever {@code CustomerMapper} is used.</p>
 *
 * <p>Mapping summary:
 * <ul>
 *   <li>{@link #dtoToCustomer}         — create DTO → new entity (audit fields ignored)</li>
 *   <li>{@link #entityToResponse}      — entity → response DTO (read-only projection)</li>
 *   <li>{@link #updateCustomerFromDto} — update DTO → existing entity (audit fields protected)</li>
 * </ul>
 * </p>
 */
@Mapper
public interface CustomerMapper {

    /**
     * Maps a create request DTO to a new {@link Customer} entity.
     *
     * <p>Fields ignored here are managed exclusively by JPA/Hibernate and must not be
     * set from user input:
     * <ul>
     *   <li>{@code id}        — generated by {@code @UuidGenerator} on first persist</li>
     *   <li>{@code version}   — managed by Hibernate optimistic locking</li>
     *   <li>{@code createdAt} — set by Spring Data JPA Auditing on insert</li>
     *   <li>{@code updatedAt} — set by Spring Data JPA Auditing on every update</li>
     *   <li>{@code orders}    — a customer starts with no orders; this collection is managed
     *                           through {@link com.restmvc.beer_store.entities.BeerOrder}</li>
     * </ul>
     * </p>
     *
     * @param customerCreateRequestDTO the validated create request
     * @return a new, unmapped {@link Customer} entity ready to be persisted
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "version", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    @Mapping(target = "orders", ignore = true)
    Customer dtoToCustomer(CustomerCreateRequestDTO customerCreateRequestDTO);

    /**
     * Maps a {@link Customer} entity to a response DTO.
     *
     * <p>The {@code orders} field in {@link CustomerResponseDTO} is mapped from the entity's
     * {@code orders} collection. This method must be called <strong>inside an active
     * transaction</strong> (e.g. within a {@code @Transactional} service method) to avoid
     * a {@code LazyInitializationException} — {@code Customer.orders} is {@code LAZY} fetched.</p>
     *
     * @param customer the managed entity to map
     * @return a {@link CustomerResponseDTO} with all customer fields including order summaries
     */
    CustomerResponseDTO entityToResponse(Customer customer);

    /**
     * Updates an existing {@link Customer} entity in-place from a request DTO.
     *
     * <p>Same fields are ignored as in {@link #dtoToCustomer} — audit fields and ID must
     * never be overwritten by user input. MapStruct writes directly into the {@code customer}
     * parameter (the {@code @MappingTarget}), so Hibernate detects the changes and issues
     * an UPDATE on the next flush.</p>
     *
     * @param customerCreateRequestDTO the validated update request
     * @param customer                 the managed entity to update (modified in-place)
     * @return the same (modified) entity — returned for convenience; not a new instance
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "version", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    @Mapping(target = "orders", ignore = true)
    Customer updateCustomerFromDto(CustomerCreateRequestDTO customerCreateRequestDTO, @MappingTarget Customer customer);
}
